DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS reposts;
DROP TABLE IF EXISTS bookmarks;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;

DROP FUNCTION IF EXISTS set_updated_at;