// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/storage/storage.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStorageServiceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageServiceHealthRequest) Reset() {
	*x = GetStorageServiceHealthRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageServiceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageServiceHealthRequest) ProtoMessage() {}

func (x *GetStorageServiceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageServiceHealthRequest.ProtoReflect.Descriptor instead.
func (*GetStorageServiceHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{0}
}

type GetStorageServiceHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageServiceHealthResponse) Reset() {
	*x = GetStorageServiceHealthResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageServiceHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageServiceHealthResponse) ProtoMessage() {}

func (x *GetStorageServiceHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageServiceHealthResponse.ProtoReflect.Descriptor instead.
func (*GetStorageServiceHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetStorageServiceHealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetStorageServiceHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStorageServiceHealthResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *GetStorageServiceHealthResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploaderId    string                 `protobuf:"bytes,1,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMediaRequest) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *UploadMediaRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadMediaRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadMediaRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	StorageKey    string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *UploadMediaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadMediaResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadMediaResponse) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *UploadMediaResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadMediaResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UploadMediaResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_storage_storage_proto protoreflect.FileDescriptor

const file_proto_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/storage/storage.proto\x12\astorage\" \n" +
	"\x1eGetStorageServiceHealthRequest\"\x84\x01\n" +
	"\x1fGetStorageServiceHealthResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAt\"\x8e\x01\n" +
	"\x12UploadMediaRequest\x12\x1f\n" +
	"\vuploader_id\x18\x01 \x01(\tR\n" +
	"uploaderId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"\xb3\x01\n" +
	"\x13UploadMediaResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2\xba\x01\n" +
	"\x0eStorageService\x12^\n" +
	"\tGetHealth\x12'.storage.GetStorageServiceHealthRequest\x1a(.storage.GetStorageServiceHealthResponse\x12H\n" +
	"\vUploadMedia\x12\x1b.storage.UploadMediaRequest\x1a\x1c.storage.UploadMediaResponseB\"Z threadly/proto/storage;storagev1b\x06proto3"

var (
	file_proto_storage_storage_proto_rawDescOnce sync.Once
	file_proto_storage_storage_proto_rawDescData []byte
)

func file_proto_storage_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)))
	})
	return file_proto_storage_storage_proto_rawDescData
}

var file_proto_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_storage_storage_proto_goTypes = []any{
	(*GetStorageServiceHealthRequest)(nil),  // 0: storage.GetStorageServiceHealthRequest
	(*GetStorageServiceHealthResponse)(nil), // 1: storage.GetStorageServiceHealthResponse
	(*UploadMediaRequest)(nil),              // 2: storage.UploadMediaRequest
	(*UploadMediaResponse)(nil),             // 3: storage.UploadMediaResponse
}
var file_proto_storage_storage_proto_depIdxs = []int32{
	0, // 0: storage.StorageService.GetHealth:input_type -> storage.GetStorageServiceHealthRequest
	2, // 1: storage.StorageService.UploadMedia:input_type -> storage.UploadMediaRequest
	1, // 2: storage.StorageService.GetHealth:output_type -> storage.GetStorageServiceHealthResponse
	3, // 3: storage.StorageService.UploadMedia:output_type -> storage.UploadMediaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_storage_storage_proto_init() }
func file_proto_storage_storage_proto_init() {
	if File_proto_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_storage_proto = out.File
	file_proto_storage_storage_proto_goTypes = nil
	file_proto_storage_storage_proto_depIdxs = nil
}
