// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/feed/feed.proto

package feedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedServiceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedServiceHealthRequest) Reset() {
	*x = GetFeedServiceHealthRequest{}
	mi := &file_proto_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedServiceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedServiceHealthRequest) ProtoMessage() {}

func (x *GetFeedServiceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedServiceHealthRequest.ProtoReflect.Descriptor instead.
func (*GetFeedServiceHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{0}
}

type GetFeedServiceHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedServiceHealthResponse) Reset() {
	*x = GetFeedServiceHealthResponse{}
	mi := &file_proto_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedServiceHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedServiceHealthResponse) ProtoMessage() {}

func (x *GetFeedServiceHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedServiceHealthResponse.ProtoReflect.Descriptor instead.
func (*GetFeedServiceHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeedServiceHealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetFeedServiceHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetFeedServiceHealthResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *GetFeedServiceHealthResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

var File_proto_feed_feed_proto protoreflect.FileDescriptor

const file_proto_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x15proto/feed/feed.proto\x12\x04feed\"\x1d\n" +
	"\x1bGetFeedServiceHealthRequest\"\x81\x01\n" +
	"\x1cGetFeedServiceHealthResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAt2a\n" +
	"\vFeedService\x12R\n" +
	"\tGetHealth\x12!.feed.GetFeedServiceHealthRequest\x1a\".feed.GetFeedServiceHealthResponseB\x1cZ\x1athreadly/proto/feed;feedv1b\x06proto3"

var (
	file_proto_feed_feed_proto_rawDescOnce sync.Once
	file_proto_feed_feed_proto_rawDescData []byte
)

func file_proto_feed_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feed_feed_proto_rawDesc), len(file_proto_feed_feed_proto_rawDesc)))
	})
	return file_proto_feed_feed_proto_rawDescData
}

var file_proto_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_feed_feed_proto_goTypes = []any{
	(*GetFeedServiceHealthRequest)(nil),  // 0: feed.GetFeedServiceHealthRequest
	(*GetFeedServiceHealthResponse)(nil), // 1: feed.GetFeedServiceHealthResponse
}
var file_proto_feed_feed_proto_depIdxs = []int32{
	0, // 0: feed.FeedService.GetHealth:input_type -> feed.GetFeedServiceHealthRequest
	1, // 1: feed.FeedService.GetHealth:output_type -> feed.GetFeedServiceHealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_feed_feed_proto_init() }
func file_proto_feed_feed_proto_init() {
	if File_proto_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feed_feed_proto_rawDesc), len(file_proto_feed_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_feed_proto_depIdxs,
		MessageInfos:      file_proto_feed_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_feed_proto = out.File
	file_proto_feed_feed_proto_goTypes = nil
	file_proto_feed_feed_proto_depIdxs = nil
}
