// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/content/content.proto

package contentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContentServiceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentServiceHealthRequest) Reset() {
	*x = GetContentServiceHealthRequest{}
	mi := &file_proto_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentServiceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentServiceHealthRequest) ProtoMessage() {}

func (x *GetContentServiceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentServiceHealthRequest.ProtoReflect.Descriptor instead.
func (*GetContentServiceHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{0}
}

type GetContentServiceHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentServiceHealthResponse) Reset() {
	*x = GetContentServiceHealthResponse{}
	mi := &file_proto_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentServiceHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentServiceHealthResponse) ProtoMessage() {}

func (x *GetContentServiceHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentServiceHealthResponse.ProtoReflect.Descriptor instead.
func (*GetContentServiceHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *GetContentServiceHealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetContentServiceHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetContentServiceHealthResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *GetContentServiceHealthResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

var File_proto_content_content_proto protoreflect.FileDescriptor

const file_proto_content_content_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/content/content.proto\x12\acontent\" \n" +
	"\x1eGetContentServiceHealthRequest\"\x84\x01\n" +
	"\x1fGetContentServiceHealthResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAt2p\n" +
	"\x0eContentService\x12^\n" +
	"\tGetHealth\x12'.content.GetContentServiceHealthRequest\x1a(.content.GetContentServiceHealthResponseB\"Z threadly/proto/content;contentv1b\x06proto3"

var (
	file_proto_content_content_proto_rawDescOnce sync.Once
	file_proto_content_content_proto_rawDescData []byte
)

func file_proto_content_content_proto_rawDescGZIP() []byte {
	file_proto_content_content_proto_rawDescOnce.Do(func() {
		file_proto_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_content_proto_rawDesc), len(file_proto_content_content_proto_rawDesc)))
	})
	return file_proto_content_content_proto_rawDescData
}

var file_proto_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_content_content_proto_goTypes = []any{
	(*GetContentServiceHealthRequest)(nil),  // 0: content.GetContentServiceHealthRequest
	(*GetContentServiceHealthResponse)(nil), // 1: content.GetContentServiceHealthResponse
}
var file_proto_content_content_proto_depIdxs = []int32{
	0, // 0: content.ContentService.GetHealth:input_type -> content.GetContentServiceHealthRequest
	1, // 1: content.ContentService.GetHealth:output_type -> content.GetContentServiceHealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_content_content_proto_init() }
func file_proto_content_content_proto_init() {
	if File_proto_content_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_content_proto_rawDesc), len(file_proto_content_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_content_content_proto_goTypes,
		DependencyIndexes: file_proto_content_content_proto_depIdxs,
		MessageInfos:      file_proto_content_content_proto_msgTypes,
	}.Build()
	File_proto_content_content_proto = out.File
	file_proto_content_content_proto_goTypes = nil
	file_proto_content_content_proto_depIdxs = nil
}
