// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/user/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserServiceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserServiceHealthRequest) Reset() {
	*x = GetUserServiceHealthRequest{}
	mi := &file_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserServiceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserServiceHealthRequest) ProtoMessage() {}

func (x *GetUserServiceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserServiceHealthRequest.ProtoReflect.Descriptor instead.
func (*GetUserServiceHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

type GetUserServiceHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserServiceHealthResponse) Reset() {
	*x = GetUserServiceHealthResponse{}
	mi := &file_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserServiceHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserServiceHealthResponse) ProtoMessage() {}

func (x *GetUserServiceHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserServiceHealthResponse.ProtoReflect.Descriptor instead.
func (*GetUserServiceHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserServiceHealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetUserServiceHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUserServiceHealthResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *GetUserServiceHealthResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

var File_proto_user_user_proto protoreflect.FileDescriptor

const file_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user/user.proto\x12\x04user\"\x1d\n" +
	"\x1bGetUserServiceHealthRequest\"\x81\x01\n" +
	"\x1cGetUserServiceHealthResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAt2a\n" +
	"\vUserService\x12R\n" +
	"\tGetHealth\x12!.user.GetUserServiceHealthRequest\x1a\".user.GetUserServiceHealthResponseB\x1cZ\x1athreadly/proto/user;userv1b\x06proto3"

var (
	file_proto_user_user_proto_rawDescOnce sync.Once
	file_proto_user_user_proto_rawDescData []byte
)

func file_proto_user_user_proto_rawDescGZIP() []byte {
	file_proto_user_user_proto_rawDescOnce.Do(func() {
		file_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)))
	})
	return file_proto_user_user_proto_rawDescData
}

var file_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_user_proto_goTypes = []any{
	(*GetUserServiceHealthRequest)(nil),  // 0: user.GetUserServiceHealthRequest
	(*GetUserServiceHealthResponse)(nil), // 1: user.GetUserServiceHealthResponse
}
var file_proto_user_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.GetHealth:input_type -> user.GetUserServiceHealthRequest
	1, // 1: user.UserService.GetHealth:output_type -> user.GetUserServiceHealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_user_proto_init() }
func file_proto_user_user_proto_init() {
	if File_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_user_proto_goTypes,
		DependencyIndexes: file_proto_user_user_proto_depIdxs,
		MessageInfos:      file_proto_user_user_proto_msgTypes,
	}.Build()
	File_proto_user_user_proto = out.File
	file_proto_user_user_proto_goTypes = nil
	file_proto_user_user_proto_depIdxs = nil
}
